# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.PositiveIntegerField()),
                ('member_name', models.CharField(max_length=250)),
                ('email_id', models.EmailField(max_length=250)),
                ('phone_number', models.PositiveIntegerField(blank=True)),
                ('maintenance_bill', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('job', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('table_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.Table')),
                ('complaint_date', models.DateTimeField(auto_now_add=True)),
                ('urgency_level', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
            bases=('page.table',),
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('table_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.Table')),
                ('event_date', models.DateField()),
                ('budget', models.PositiveIntegerField()),
            ],
            bases=('page.table',),
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('table_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.Table')),
                ('urgency_level', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
            bases=('page.table',),
        ),
        migrations.AddField(
            model_name='attendance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Staff'),
        ),
    ]
