# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name_plural': 'attendance'},
        ),
        migrations.AlterModelOptions(
            name='complaints',
            options={'verbose_name_plural': 'complaints'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='notices',
            options={'verbose_name_plural': 'notices'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'staff'},
        ),
    ]
