# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20170221_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
