# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20170221_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='complaint_date',
        ),
    ]
