# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_remove_complaints_complaint_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
